### ISSUE TITLE
reviews from colleagues 

### ISSUE THREAD

**Issue by jhamman** [jhamman/xarray_paper#6]
## Reviewer 1
- [ ] My one non-nit comment is that you don't emphasize the out-of-core abilities as much as you should. The ability to work with gigantic virtual datasets is awesome.

**_Response: @shoyer to respond**_
#### "Nits"
- [x] both "pandas" and "netCDF" usually don't have their first letters capitalized, except when they are the first word in a sentence. There's also a mixture of "Dask" and "dask" in the text.

**_Response: This is a good point. I've made corrections to the nominclature used by xarray, dask, netCDF, and pandas. I've also highlighted the xarray name throughout the text**_
- [x] "fixed rank design them" → "fixed-rank design makes it" I'm not sure that "rank" is the best word here since its meaning gets confused with "matrix rank". Perhaps "order", as in "tensor order"?

**_Response: Typo fixed.  I think rank is the appropriate term here ([link](https://en.wikipedia.org/wiki/Rank_%28computer_programming%29)).**_
- [x] the color bar label in figure 1 should say "degree C" or equivalent.
- [x] I don't think you need a comma separating "longitude" and "latitude" at the end of the caption for figure 1.

**_Response: Fixed.**_
- [x] the hyphenation of "timestamps" in "For example, time series data includes timestamps" is odd.

**_Response: Fixed.**_
- [x] "preserving the consistent labels" → "preserving consistent labels"

**_Response: Fixed.**_
- [x] "principle data structure" → "principal data structure"

**_Response: Fixed.**_
- [ ] the caption for figure 2 implicitly raises the confusion between dimensions and coordinates by not mentioning a time coordinate. You might want to mention the time coordinate and perhaps also add a comment that there's further explanation in the text

**_Response: @shoyer to respond**_
- [x] do you want to add a citation or reference for the Bottleneck library?

**_Response: Done.  See also: https://github.com/kwgoodman/bottleneck/issues/138.**_
- [x] I am reminded that you are not a fan of the serial comma.
## Reviewer 2
- [ ] I'll iterate Todd's comments about definitely expanding upon the capabilities of dask + xarray.

**_Response: @shoyer to respond**_
- [x] "Raw N-dimensional arrays of numbers" is an odd way to phrase it, maybe "Unlabeled, N-dimensional arrays of numbers"? I get what you're trying to say, calling them "raw" just reads strangely.

**_Response: Done.**_
- [ ] I think the coordinates structure could be described in more detail than just referring to Figure 2. I also thought that netCDF files required coordinate variables but reading up on it proved me wrong.

**_Response: @shoyer to respond**_
- [x] nit: I would maybe write GRIB as GRIB1/2, as there is a difference between the two formats (and PyNIO can read both).

**_Response: Done.**_
- [x] "Xarray supports direct serialization and I/O to several file formats including pickle, NetCDF, OPeNDAP, GRIB, and HDF by integrating with third-party libraries." That's mostly true, I think xarray can only read grib files and not write them, right?

**_Response: Clarified that OPeNDAP and GRIB1/2 backends are "read-only"**_
## Reviewer 3
- [x] abstract: I think it is a bit short, and I find it a bit defensive and oriented towards specialists. In particular, the following sentence: "It provides a Pandas-like and Pandas-compatible toolkit for analytics on multi-dimensional arrays, rather than the tabular data format for which Pandas excels." is the only sentence which actually says what xarray is for, but at the same time it doesn't say more than: "we do like Pandas but for N-dimensions". I believe that xarray does a bit more than that! And what about readers who don't know what pandas is? I would also stress the fact that xarray operates perfectly with netcdf, and allows does out-of-core computations, which is awesome. Basically, xarray is the tool of choice for everyone: from engineers doing low-level data processing on the server side to scientists doing geoscientific data exploration on their laptop of for a classroom.

**_Response: Agreed.  I've taken another swing at the abstract.  @shoyer, take another pass too!**_
- [x] P5, "Interactivity with Pandas: One of the most important features of Xarray ...": to me, this is not the most important feature of xarray ;-). I would remove this statement.

**_Response: Agreed, rephrased to call this a "key feature"**_
- [x] maybe I missed it, but one of the nice features of xarray is the vectorized arithmetic based on dimension names and coordinates, which is extremely useful I think.

**_Response: This was briefly mentioned in the Core xarray features section, I've made it a bit clearer.**_

**Comment by jhamman** [comment]
@shoyer - this is ready for you to take another look at.  I left a few issues above for you following my last commit ( 0cde2aa ).

**Comment by shoyer** [comment]
Thanks, I'll take a look later today.
